### ISSUE TITLE
Error Object is Always null

### ISSUE THREAD

**Issue by cjihrig** [deanmao/node-chimera#10]
The error parameter of callback is always null.  Also, chimera does not terminate in Ubuntu, as mentioned in #9.

var Chimera = require("chimera").Chimera;
var chimera = new Chimera();

chimera.perform({
  url: "http://www.google.com",
  locals: {
  },
  run: function(callback) {
    callback("foo", "bar");
  },
  callback: function(err, result) {
    console.log(arguments);
    chimera.close();
  }
});

**Comment by deanmao** [comment]
thanks for reporting the bug.
