### ISSUE TITLE
Ability to Silence WebKit

### ISSUE THREAD

**Issue by cjihrig** [deanmao/node-chimera#11]
Is there a way to silence WebKit messages?  For example, messages about insecure content when a HTTPS site loads a HTTP resource.  This would be a great feature to have.

**Comment by deanmao** [comment]
no way to silence right now, but I could add that as a feature of course.  I just have some really basic `cout <<` in the code for debugging purposes.

**Comment by cjihrig** [comment]
@deanmao I would like to contribute to this project.  Unfortunately, I'm having a lot of issues building on Ubuntu.  Particularly, the compile_qt.sh script is complaining that I don't have 'make' installed, even though I do.

**Comment by Trindaz** [comment]
@cjihrig I had the same issue on Mac OS X. The problem has two causes. 1) The qt source bundled with chimera is missing the contents of qt/config.tests so qt/config will never discover the make path. 2) The .zip file from the qt website with the qt source uses non-Unix line endings. This will cause all of kinds of other errors, one of which for me was not finding make, so make sure you use the .tar.gz archive from the qt website and not the .zip option when downloading the 4.8.4 source.
