### ISSUE TITLE
Segmentation fault: 11 on Mac OS X 10.7.3 (64-bit)

### ISSUE THREAD

**Issue by Trindaz** [deanmao/node-chimera#13]
When running examples/example.js I get output:

Using the chimera in lib
Segmentation fault: 11

**Comment by deanmao** [comment]
it seems like you got it running in your later bug reports...

**Comment by christhorwarth** [comment]
Note - I had this error and the only way to get past it was to have a timeout for 500ms after the Chimera lib is loaded.

**Comment by kristjanjansen** [comment]
@christhorwarth can you provide an example how to get past this?
