### ISSUE TITLE
qt folder missing in project root

### ISSUE THREAD

**Issue by Trindaz** [deanmao/node-chimera#14]
I installed Chimera using `npm install` but it didn't create a qt folder in the chimera/ project root folder. This means the manual compile instructions fail (no folder qt to cd in to).

**Comment by Trindaz** [comment]
Download this tarball for qt 4.8.4: http://releases.qt-project.org/qt4/source/qt-everywhere-opensource-src-4.8.4.tar.gz

Extract it to /chimera/qt

Then you should have the required files for running /scripts/compile_qt.sh

**Comment by deanmao** [comment]
npm install will not copy everything from this github repo, otherwise the install would be way too big!  You can see what directories are ignored from the .npmignore file.  I don't expect people to compile openssl & qt.
