### ISSUE TITLE
./scripts/compile_binary.sh throws error fatal error: 'QtWebKit/QWebPage' file not found

### ISSUE THREAD

**Issue by Trindaz** [deanmao/node-chimera#16]
The line in console output that displays the error:

../src/chimera.h:5:10: fatal error: 'QtWebKit/QWebPage' file not found

This was right after successfully running compile_qt.sh for qt 4.8.4

**Comment by deanmao** [comment]
looks like the compile is missing some stuff....

**Comment by underbyte** [comment]
Was this fix ever checked in? I'm trying to build it on ubuntu 64bit and getting that error. Looks like "ln -s ../../qt/include/QtWebKit ." need to be added to the compile_qt.sh

I'm trying to build chimera on a ubuntu 64bit are these steps correct?
1. clone repo
2. untar qt 4.8.5 from http://releases.qt-project.org/qt4/source/qt-everywhere-opensource-src-4.8.4.tar.gz into project and rename to qt
3. execute compile_openssl.sh, compile_qt.sh, compile_binary.sh

**Comment by fabio-fonseca-olx** [comment]
where is compile_binary.sh??
