### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xemware** [deanmao/node-chimera#2]
Nice one - a reference to this project popped up on twitter today via NodeJs Community

Any interest in making chimera available under an alternate license like MIT?
I think the first node module I've seen with GPL applied.  

I'm still working my way through various assessments of license compatibility but may have an issue using it going forward, and I'd really like to - it blows away my own effort in wrapping QtWebKit.

Cheers

**Comment by deanmao** [comment]
Just curious, i've been getting lots of traffic suddenly on chimera -- where did this show up?  I haven't updated chimera in a while, so it's kind of strange to suddenly see traffic there.

Yeah, I'm open to making it MIT.

**Comment by TimNZ** [comment]
https://twitter.com/NodeJsCommunity/status/286651834779721729

I think there are a few people that search for 'node js' stuff and they managed to stumble across chimera.  Which is very handy for me, timing was perfect.

MIT is perfect, thanks.

**Comment by jacobmarble** [comment]
Also, HN: http://news.ycombinator.com/item?id=5000306

**Comment by TimNZ** [comment]
My effort is more of a simple wrapper.  Tests fine on Win/Linux, but I expect your use of ev is perhaps the right way to go.
I'll fork it and look to add some of the things I did.

One thing mine does is let you show a QMainWindow that wraps a QWebView so people can interact and jump through pages and click a button in a toolbar that calls a callback passed into show()

**Comment by deanmao** [comment]
congrats, the license is now BSD.  If you want MIT, you'll have to fork it and relicense it :-)

**Comment by TimNZ** [comment]
Lovely!

**Comment by deanmao** [comment]
Added some basic documentation...  also closing out this request.
