### ISSUE TITLE
chimera is not terminating

### ISSUE THREAD

**Issue by mren** [deanmao/node-chimera#9]
Hey,

i just tried out your example on a mac

``` javascript
var Chimera = require('chimera').Chimera;

var c = new Chimera();
c.perform({
  url: "http://www.google.com",
  locals: {

  },
  run: function(callback) {
    callback(null, "success");
  },
  callback: function(err, result) {
    console.log('finished', err, result);
    c.close()
  }
});
```

if i execute the script with `node chimera.js` i get the 'finished' message, but the script is stil running.

how can i terminate the script in a safe manner?

cheers mark

**Comment by deanmao** [comment]
I'll take a look...

**Comment by mren** [comment]
any updates?

**Comment by deanmao** [comment]
Hey sorry, on vacation right now, I'll take a look soon.

**Comment by Meekohi** [comment]
I have the same issue. 

Mac OSX
Node v0.8.20
Chimera 0.3.2
